corona/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',signin,name='signin'),
    path('patients/',patients,name='patients'),
    path('doctors/',doctors,name='doctors'),
    path('tests/',tests,name='tests'),
    path('drugs/',drugs,name='drugs'),
    path('blank/',blank,name='blank'),
    path('logout/',logout,name='logout'),
    path('profile/',profile,name='profile'),
    path('orders/',orders,name='orders'),
    path('mails/',mail,name='mail'),
    path('work-schedule/',work_schedule,name='work_schedule'),






]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class WebsiteUser(models.Model):
    user_id = models.CharField(null=True,blank=True,max_length=150,unique=True)
    user_name = models.CharField(null=True,blank=True,max_length=150)
    user_last_name = models.CharField(null=True,blank=True,max_length=150)
    user_address = models.CharField(null=True,blank=True,max_length=1000)
    user_phone = models.CharField(null=True,blank=True,max_length=1000)
    user_birthday  = models.CharField(null=True,blank=True, max_length=50)
    salary = models.CharField(null=True,blank=True, max_length=50)

    user_status = models.CharField(null=True,blank=True,max_length=150,choices=(('G',"Good"),('NG',"Not Good")))

    user_type  = models.CharField(null=True,blank=True, choices=(('A',"ADMIN"),('D',"DOCTOR") ,('P',"PATIENT")),max_length=400)
    user_password = models.CharField(null=True,blank=True,max_length=150)
    
    added = models.DateTimeField(auto_now=True)
    

   
            
    def __str__(self):
        return u'{0}'.format(self.user_id)

class Test(models.Model):
    """Model definition for Test."""
    test_id = models.CharField(null=True,blank=True,max_length=150,unique=True)
    test_number = models.CharField(null=True,blank=True,max_length=150,unique=True)
    patient = models.ForeignKey(WebsiteUser,null=True,blank=True, on_delete=models.CASCADE,related_name="tests")
    test_date = models.DateTimeField(null=True,blank=True)
    test_type  = models.CharField(null=True,blank=True, max_length=50 , choices=(('B',"BLOOD"),('C',"CORONA")))
    added = models.DateTimeField(auto_now=True)


    class Meta:
        """Meta definition for Test."""

        verbose_name = 'Test'
        verbose_name_plural = 'Tests'

    def __str__(self):
        """Unicode representation of Test."""
        return u'{0}'.format(self.test_id)


class Drug(models.Model):
    """Model definition for Drug."""

    drug_name  = models.CharField(null=True,blank=True, max_length=50,unique=True)
    added = models.DateTimeField(auto_now=True)


    class Meta:
        """Meta definition for Drug."""

        verbose_name = 'Drug'
        verbose_name_plural = 'Drugs'

    def __str__(self):
        """Unicode representation of Drug."""
        return u'{0}'.format(self.drug_name)

class Order(models.Model):
    """Model definition for Order."""

    order_id = models.CharField(null=True,blank=True, max_length=50,unique=True)
    order_name  = models.CharField(null=True,blank=True, max_length=50)
    order_description  = models.CharField(null=True,blank=True, max_length=5000)
    order_amount  = models.CharField(null=True,blank=True, max_length=50)
    order_quantity  = models.CharField(null=True,blank=True, max_length=50)
    order_price  = models.CharField(null=True,blank=True, max_length=50)

    added = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Order."""

        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        """Unicode representation of Order."""
        return u'{0}'.format(self.order_id)


class WorkSchedule(models.Model):
    """Model definition for WorkSchedule."""

    doctor = models.ForeignKey(WebsiteUser,null=True,blank=True, on_delete=models.CASCADE)
    start = models.DateTimeField(null=True,blank=True, auto_now=False, auto_now_add=False)
    end = models.DateTimeField(null=True,blank=True, auto_now=False, auto_now_add=False)
    added = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for WorkSchedule."""

        verbose_name = 'WorkSchedule'
        verbose_name_plural = 'WorkSchedules'

    def __str__(self):
        """Unicode representation of WorkSchedule."""
        return u'{0}'.format(self.doctor.user_id)

class Mail(models.Model):
    """Model definition for Mail."""
    sender = models.ForeignKey(WebsiteUser,null=True,blank=True, on_delete=models.CASCADE)
    reciever = models.ForeignKey(WebsiteUser,null=True,blank=True, on_delete=models.CASCADE,related_name="recieved_mails")
    message = models.CharField(null=True,blank=True, max_length=50000)
    added = models.DateTimeField(auto_now=True)

    

    class Meta:
        """Meta definition for Mail."""

        verbose_name = 'Mail'
        verbose_name_plural = 'Mails'

    def __str__(self):
        """Unicode representation of Mail."""
        pass

templates/common/blank.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>Listing</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&amp;display=swap" rel="stylesheet">
    <link href="{%static '' %}vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="{%static '' %}vendor/assets/css/plugins.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL CUSTOM STYLES -->
    <link href="{%static '' %}vendor/assets/css/scrollspyNav.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{%static '' %}vendor/assets/css/forms/theme-checkbox-radio.css">
    <link href="{%static '' %}vendor/assets/css/tables/table-basic.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL CUSTOM STYLES -->
</head>
<body class="sidebar-noneoverflow" data-spy="scroll" data-target="#navSection" data-offset="140">


    <!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>



    </div>
    <!-- END MAIN CONTAINER -->

    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="{%static '' %}vendor/assets/js/libs/jquery-3.1.1.min.js"></script>
    <script src="{%static '' %}vendor/bootstrap/js/popper.min.js"></script>
    <script src="{%static '' %}vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="{%static '' %}vendor/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="{%static '' %}vendor/assets/js/app.js"></script>
    
    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>
    <script src="{%static '' %}vendor/plugins/highlight/highlight.pack.js"></script>
    <script src="{%static '' %}vendor/assets/js/custom.js"></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->

    <!-- BEGIN PAGE LEVEL CUSTOM SCRIPTS -->
    <script src="{%static '' %}vendor/assets/js/scrollspyNav.js"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        checkall('todoAll', 'todochkbox');
        $('[data-toggle="tooltip"]').tooltip()
    </script>

    <script>
       var DeletePatient = (id)=>{
        console.log(id);
            swal({
      title: "Are you sure?",
      text: "You are about to Delete the patient Data,Are you sure?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
        console.log(willDelete);
      if (willDelete) {
        $.post( "{% url 'table' %}", {type:"delete", id,csrfmiddlewaretoken: '{{ csrf_token }}'})
            .done(function( data ) {
    
    
            })
      }
      document.location.reload()
      })
          
         
       }
    </script>

    <script>

  $('form').submit(function (ev) {
    
    
    $('button').prop('disabled',true)
    
    ev.preventDefault();
    
    if (this.method != 'get'){
    var formData = new FormData($(this)[0]);
    
    
    
    $.ajax({
    type: 'POST',
    url: "{%url 'table'%}",
    data: formData,
    async: true,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
    
    $('button').prop('disabled',false)
    
    console.log(data)
    
    if (data.status=='success'){
       
    swal({  
        text: data.message,        
        icon: "success",
        timer: 3000,
        }).then(function () { window.location= '{%url "table"%}'}, 2000)
    }
    else{
        swal({  
        text: data.message,        
        icon: "warning",
        timer: 3000,
        })
    }
    
    
    
    }
    
    });
    
    
    }
    else{
    
    this.submit()
    
    }
    
    
    
    });
    
   
    </script>
    <!-- END PAGE LEVEL CUSTOM SCRIPTS -->
</body>
</html>

templates/common/doctors.html
{%extends 'common/base.html'%}
{%load static%}
{%block dactive %}active {%endblock%}

{%block container%}
    <div class="modal fade" id="addContactModal" tabindex="-1" role="dialog" aria-labelledby="addContactModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 60%;" role="document">
            <div class="modal-content">
                <div class="modal-body">         
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Add Doctor</h4>
                            </div>                                                                        
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <form id="add_vendor_form" method="POST">
                            {%csrf_token%}
                            <input type="hidden" name="type" value="add">
                          
                            <div class="form-row mb-4">
                                
                                <div class="form-group col-md-6">
                                    <label for="user_id">User Id</label>
                                    <input  type="text" name="user_id" class="form-control" id="user_id">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_name">First Name</label>
                                    <input  type="text" name="user_name" class="form-control" id="user_name">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_last_name"> Last Name</label>
                                    <input  type="text" name="user_last_name" class="form-control" id="user_last_name" >
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_address">Address</label>
                                  <textarea  id="user_address" name="user_address" class="form-control"></textarea>

                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_phone">Phone Number</label>
                                    <input type="number" name="user_phone" class="form-control" id="user_phone">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_birtday">Birth Day</label>
                                    <input type="date" name="user_birtday" class="form-control" id="user_birtday">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="salary">salary</label>
                                    <input type="number" name="salary" class="form-control" id="salary">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="user_status"> Status</label>
                                    <select class="form-control" name="user_status" id="user_status">
                                        <option value="">Please select</option>
                                        <option value="G">Good</option>
                                        <option value="NG">Not Good</option>

                                    </select>
                                </div>


                                <div class="form-group col-md-6">
                                    <label for="password">Password</label>
                                    <input type="password" name="password" class="form-control" id="password">
                                </div>
                             
                            </div>
                           
                            <button id="btn-edit" type="submit" class="float-left btn primary">Submit</button>
    
                            <button style="margin-left: 20px;" class="btn" data-dismiss="modal"> <i class="flaticon-delete-1"></i> Discard</button>
                        </form>
                    </div>   
                </div>
                
            </div>
        </div>
    </div>
 
    <!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

     
        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            
            <div class="container" style="max-width: 100% !important;">
                <div class="container">

                 

                    <div class="row layout-top-spacing">
                      
                        
                        <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-header">
                                    <div class="row">
                                        <div class="col-xl-10 col-md-10 col-sm-10 col-10">
                                            <h4>Doctors</h4>
                                        </div> 
                                        <div class="col-2 pt-3">
                                            <button data-toggle="modal" data-target="#addContactModal" class="btn btn-light-default" style="float: right;"> + Add Doctor</button>

                                        </div>    

                                    </div>
                                </div>
                                <div class="widget-content widget-content-area">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover mb-4">
                                            <thead>
                                                <tr>
                                                    <th>User ID</th>
                                                    <th>First Name</th>
                                                   
                                                    <th>Last Name</th>
                                                    <th>Adress</th>
                                                    <th>Phone Number</th>


                                                    
                                                    
                                                    <th class="text-center">Status</th>
                                                    <th>Added Date</th>

                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {%for p in doctors%}
                                                <tr>
                                                    <td>{{p.user_id}}</td>
                                                    <td>{{p.user_name}}</td>
                                                    <td>{{p.user_last_name}}</td>
                                                    <td>{{p.user_address}}</td>
                                                    <td>{{p.user_phone}}</td>

                                                    <td class="text-center"><span class="text-success">{{p.get_user_status_display}}</span></td>
                                                    <td>{{p.added|date:"D d M Y"}}</td>

                                                    <td class="text-center" ><svg onclick="DeletePatient({{p.id}})" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 icon"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg></td>
                                                </tr>
                                              {%endfor%}
                                            </tbody>
                                        </table>
                                    </div>

                                

                                </div>
                            </div>
                        </div>
                    

                     

                    </div>

                </div>
                </div>
      
        </div>
        <!--  END CONTENT AREA  -->

    </div>
    <!-- END MAIN CONTAINER -->

    {%endblock%}
    
 
{%block extrajs%}

    <script>
        checkall('todoAll', 'todochkbox');
        $('[data-toggle="tooltip"]').tooltip()
    </script>

    <script>
       var DeletePatient = (id)=>{
        console.log(id);
            swal({
      title: "Are you sure?",
      text: "You are about to Delete the User Data,Are you sure?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
        console.log(willDelete);
      if (willDelete) {
        $.post( "{% url 'doctors' %}", {type:"delete", id,csrfmiddlewaretoken: '{{ csrf_token }}'})
            .done(function( data ) {
    
    
            })
      }
      document.location.reload()
      })
          
         
       }
    </script>

    <script>

  $('form').submit(function (ev) {
    
    
    $('button').prop('disabled',true)
    
    ev.preventDefault();
    
    if (this.method != 'get'){
    var formData = new FormData($(this)[0]);
    
    
    
    $.ajax({
    type: 'POST',
    url: "{%url 'doctors'%}",
    data: formData,
    async: true,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
    
    $('button').prop('disabled',false)
    
    console.log(data)
    
    if (data.status=='success'){
       
    swal({  
        text: data.message,        
        icon: "success",
        timer: 3000,
        }).then(function () { window.location= '{%url "doctors"%}'}, 2000)
    }
    else{
        swal({  
        text: data.message,        
        icon: "warning",
        timer: 3000,
        })
    }
    
    
    
    }
    
    });
    
    
    }
    else{
    
    this.submit()
    
    }
    
    
    
    });
    
   
    </script>
    <!-- END PAGE LEVEL CUSTOM SCRIPTS -->
    {%endblock%}

templates/common/tests.html
{%extends 'common/base.html'%}
{%load static%}
{%block tactive %}active {%endblock%}

<!DOCTYPE html>

{%block container%}
    <div class="modal fade" id="addContactModal" tabindex="-1" role="dialog" aria-labelledby="addContactModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 60%;" role="document">
            <div class="modal-content">
                <div class="modal-body">         
                    <div class="widget-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Add Tests</h4>
                            </div>                                                                        
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        <form id="add_vendor_form" method="POST">
                            {%csrf_token%}
                            <input type="hidden" name="type" value="add">
                          
                            <div class="form-row mb-4">
                                
                                <div class="form-group col-md-6">
                                    <label for="test_id">Test Id</label>
                                    <input  type="text" name="test_id" class="form-control" id="test_id">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="test_number">Test Number</label>
                                    <input  type="text" name="test_number" class="form-control" id="test_number">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="test_date"> Test Date</label>
                                    <input  type="date" name="test_date" class="form-control" id="test_date" >
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="patient"> Patient</label>
                                    <select class="form-control" required name="patient" id="patient">
                                        <option value="">Please select</option>
                                        {%for p in patients%}
                                        <option value="{{p.id}}">{{p.user_name}} {{p.user_last_name}}</option>
                                      {%endfor%}

                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="test_type"> Test Type</label>
                                    <select class="form-control" name="test_type" id="test_type">
                                        <option value="">Please select</option>
                                        <option value="B">Blood</option>
                                        <option value="C">Corona</option>

                                    </select>
                                </div>


                                
                             
                            </div>
                           
                            <button id="btn-edit" type="submit" class="float-left btn primary">Submit</button>
    
                            <button style="margin-left: 20px;" class="btn" data-dismiss="modal"> <i class="flaticon-delete-1"></i> Discard</button>
                        </form>
                    </div>   
                </div>
                
            </div>
        </div>
    </div>
 
    <!--  BEGIN MAIN CONTAINER  -->
    <div class="main-container" id="container">

        <div class="overlay"></div>
        <div class="search-overlay"></div>

        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            
            <div class="container" style="max-width: 100% !important;">
                <div class="container">

                 

                    <div class="row layout-top-spacing">
                      
                        
                        <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-header">
                                    <div class="row">
                                        <div class="col-xl-10 col-md-10 col-sm-10 col-10">
                                            <h4>Tests</h4>
                                        </div> 
                                        <div class="col-2 pt-3">
                                            <button data-toggle="modal" data-target="#addContactModal" class="btn btn-light-default" style="float: right;"> + Add Tests</button>

                                        </div>    

                                    </div>
                                </div>
                                <div class="widget-content widget-content-area">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-hover mb-4">
                                            <thead>
                                                <tr>
                                                    <th>Test ID</th>
                                                    <th>Test Number</th>
                                                   
                                                    <th>Patient Id</th>
                                                    <th>Patient Name</th>
                                                    <th>Test Date</th>
                                                    <th>Test Type</th>

                                                    <th>Added Date</th>
                                              

                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {%for p in tests%}
                                                <tr>
                                                    <td>{{p.test_id}}</td>
                                                    <td>{{p.test_number}}</td>
                                                    <td>{{p.patient.user_id}}</td>
                                                    <td>{{p.patient.user_name}} {{p.patient.user_last_name}}</td>
                                                    <td>{{p.test_date}}</td>
                                                    <td>{{p.get_test_type_display}}</td>

                                                    <td>{{p.added|date:"D d M Y"}}</td>

                                                    <td class="text-center" ><svg onclick="DeletePatient({{p.id}})" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 icon"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg></td>
                                                </tr>
                                              {%endfor%}
                                            </tbody>
                                        </table>
                                    </div>

                                

                                </div>
                            </div>
                        </div>
                    

                     

                    </div>

                </div>
                </div>
       
        </div>
        <!--  END CONTENT AREA  -->

    </div>
    <!-- END MAIN CONTAINER -->

    {%endblock%}
    
 
{%block extrajs%}

    <script>
        checkall('todoAll', 'todochkbox');
        $('[data-toggle="tooltip"]').tooltip()
    </script>

    <script>
       var DeletePatient = (id)=>{
        console.log(id);
            swal({
      title: "Are you sure?",
      text: "You are about to Delete the Test Data,Are you sure?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
        console.log(willDelete);
      if (willDelete) {
        $.post( "{% url 'tests' %}", {type:"delete", id,csrfmiddlewaretoken: '{{ csrf_token }}'})
            .done(function( data ) {
    
    
            })
      }
      document.location.reload()
      })
          
         
       }
    </script>

    <script>

  $('form').submit(function (ev) {
    
    
    $('button').prop('disabled',true)
    
    ev.preventDefault();
    
    if (this.method != 'get'){
    var formData = new FormData($(this)[0]);
    
    
    
    $.ajax({
    type: 'POST',
    url: "{%url 'tests'%}",
    data: formData,
    async: true,
    cache: false,
    contentType: false,
    processData: false,
    success: function (data) {
    
    $('button').prop('disabled',false)
    
    console.log(data)
    
    if (data.status=='success'){
       
    swal({  
        text: data.message,        
        icon: "success",
        timer: 3000,
        }).then(function () { window.location= '{%url "tests"%}'}, 2000)
    }
    else{
        swal({  
        text: data.message,        
        icon: "warning",
        timer: 3000,
        })
    }
    
    
    
    }
    
    });
    
    
    }
    else{
    
    this.submit()
    
    }
    
    
    
    });
    
   
    </script>
    <!-- END PAGE LEVEL CUSTOM SCRIPTS -->
    {%endblock%}